In [2]:
import numpy as np

In [3]:
x = np.arange(10)

In [4]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
x[ :5]

array([0, 1, 2, 3, 4])

In [6]:
x[4: ]

array([4, 5, 6, 7, 8, 9])

In [7]:
x[4:7]

array([4, 5, 6])

In [ ]:
x[ : :2]