In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])

In [3]:
y = np.array([3,2,1])

In [4]:
z = [21,21,21]

In [6]:
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 21, 21, 21])

In [7]:
w = np.array(['priyanka', 'regmi'])

In [8]:
np.concatenate([x,w])

array(['1', '2', '3', 'priyanka', 'regmi'], dtype='<U11')

In [10]:
grid = np.array([[1,2,3,4],[5,6,7,8]])

In [11]:
np.concatenate([grid,grid])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
np.concatenate([grid,grid], axis =1)

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8]])

In [16]:
np.hstack([x,grid])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)