In [1]:
import numpy as np

In [2]:
x = np.arange(10)

In [3]:
x1,x2,x3 = np.split(x,[3,6])

In [4]:
x1,x2,x3

(array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8, 9]))

In [5]:
grid = np.arange(16).reshape(4,4)

In [6]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [7]:
upper,lower = np.vsplit(grid,[2])

In [9]:
upper, lower

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]))