# # creating arrays

In [1]:
import numpy as np

In [2]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## creating a 3 row x 5 column matrix

In [3]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# #

In [4]:
np.full((3,5), 1.25)

array([[1.25, 1.25, 1.25, 1.25, 1.25],
       [1.25, 1.25, 1.25, 1.25, 1.25],
       [1.25, 1.25, 1.25, 1.25, 1.25]])

## creating a array with a set sequence 

In [5]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# create an array of even space between the given ranges of values

In [6]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# create a 3*3 array with mean 0 and SD 1 in given dimension

In [7]:
np.random.normal(0,1,(3,3))

array([[-1.33451461,  1.88165058, -0.30807406],
       [ 0.11954576,  0.46994639,  0.48312487],
       [ 0.04656373,  1.78671039,  0.10111323]])

# create an identy matrix

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#set a random speed

In [9]:
np.random.seed(0)

In [10]:
x1 = np.random.randint(10, size=6) #one dimention

In [11]:
x2 = np.random.randint(10, size=(3,4)) #two dimention

In [12]:
x3 = np.random.randint(10, size=(3,4,5)) #three dimention

In [13]:
print("x3 ndim:", x3.ndim)

x3 ndim: 3


In [14]:
print("x3 shape:", x3.shape)

x3 shape: (3, 4, 5)


In [15]:
print("x3 size:", x3.size)

x3 size: 60
