In [1]:
import numpy as np

creating array of 10 zeros

In [2]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
np.ones(10, dtype='float')

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.full(10,5,dtype='float')

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [15]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [34]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.random.rand(1)

array([0.08459559])

In [36]:
np.random.randn(25)

array([-1.05493894, -0.45125148, -0.12069942,  0.74319412,  0.30324247,
        1.06639418,  1.38646357, -0.02345631, -0.47887123,  0.32333096,
        0.25940966, -0.85616169,  0.76343149,  1.81779202, -0.19954196,
       -1.83489688,  0.10817909,  1.15817255,  0.08138444,  1.90141013,
       -1.44020513,  1.15074661, -1.10862403,  1.46606909, -0.35590364])

In [37]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [38]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

Numpy indexing and selection


In [40]:
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


selecting number from 12 to 25

In [54]:
mat[2: ,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

selecting number 20

In [49]:
mat[3,4]

20

selecting certain column number

In [60]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

returning last column

Sum of the matrix

In [61]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [50]:
np.sum(mat)

325

SD of the matrix mat

In [52]:
np.std(mat)

7.211102550927978

sum of the column of matrix

In [62]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])